#
# Copyright (c) 2017 Bitprim developers (see AUTHORS)
#
# This file is part of Bitprim.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

branches:
  only:
  - master
  - dev

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker

osx: &osx
   os: osx
   sudo: required
   language: generic
  #  language: python
  #  python: "3.6"

addons:
  apt:
    packages:
      - doxygen

node_js:
  - "node"
  - "8"

matrix:
   include:
      - <<: *linux
        env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6  UNIT_TESTS=true UPLOAD_PKG=true
        compiler: gcc
        python: "3.6"

      - <<: *linux
        env: C_COMPILER=gcc-6 CXX_COMPILER=g++-6  UNIT_TESTS=true
        compiler: gcc
        python: "2.7"

      # - <<: *osx
      #   osx_image: xcode7.3
      #   env: CONAN_APPLE_CLANG_VERSIONS=7.3 UNIT_TESTS=true TRAVIS_PYTHON_VERSION=2.7
      #   python: "2.7"

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 UNIT_TESTS=true TRAVIS_PYTHON_VERSION=2.7
        python: "2.7"

      # - <<: *osx
      #   osx_image: xcode7.3
      #   env: CONAN_APPLE_CLANG_VERSIONS=7.3 UNIT_TESTS=true TRAVIS_PYTHON_VERSION=3.6
      #   python: "3.6"

      - <<: *osx
        osx_image: xcode8.3
        env: CONAN_APPLE_CLANG_VERSIONS=8.1 UNIT_TESTS=true TRAVIS_PYTHON_VERSION=3.6
        python: "3.6"

install:
  # - cd ${TRAVIS_BUILD_DIR}
  # - chmod +x .travis/install.sh
  # - ./.travis/install.sh

  - set -e
  # - set -x

  - echo $TRAVIS_PYTHON_VERSION
  - echo "$TRAVIS_PYTHON_VERSION"
  - echo ${TRAVIS_PYTHON_VERSION}
  - echo "${TRAVIS_PYTHON_VERSION}"
  - echo "${TRAVIS_OS_NAME}"

  - |
    if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then
      brew update || brew update
      brew outdated pyenv || brew upgrade pyenv
      brew install pyenv-virtualenv
      brew install cmake || true

      if which pyenv > /dev/null; then
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)" 
      fi

      if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
        echo "2.7 -- 1"
      else
        echo "2.7 -- 1 -- ELSE"
      fi

      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        echo "2.7 -- 2"
      else
        echo "2.7 -- 2 -- ELSE"
      fi

      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        pyenv install 2.7.10
        pyenv virtualenv 2.7.10 conan
      else
        pyenv install 3.6.1
        pyenv virtualenv 3.6.1 conan
      fi

      pyenv rehash
      pyenv activate conan
    fi

  - pip install conan_package_tools --upgrade
  - pip install conan --upgrade
  - pip install wheel --upgrade
  - pip install twine --upgrade
  - conan user


script:
  # - cd ${TRAVIS_BUILD_DIR}
  # - chmod +x .travis/run.sh
  # - ./.travis/run.sh



  - set -e
  # - set -x

  - echo $TRAVIS_PYTHON_VERSION
  - echo "$TRAVIS_PYTHON_VERSION"
  - echo ${TRAVIS_PYTHON_VERSION}
  - echo "${TRAVIS_PYTHON_VERSION}"
  - echo "${TRAVIS_OS_NAME}"


  - |
    if [[ "${TRAVIS_OS_NAME}" != "linux" ]]; then
      if which pyenv > /dev/null; then
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"
      fi
      pyenv activate conan
    fi


  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      cd ${TRAVIS_BUILD_DIR}
      chmod a+x .travis/entrypoint.sh
      /usr/bin/docker run --rm -ti -e TRAVIS_PYTHON_VERSION=$TRAVIS_PYTHON_VERSION -e UNIT_TESTS=$UNIT_TESTS -e UPLOAD_PKG=$UPLOAD_PKG -v ${TRAVIS_BUILD_DIR}:/home/conan/project -v ${TRAVIS_BUILD_DIR}/.travis/entrypoint.sh:/tmp/entrypoint.sh lasote/conangcc63 /bin/bash -c /tmp/entrypoint.sh
    else
      # pip install -v -e .
      pip install -e .

      if [[ "${UNIT_TESTS}" == "true" ]]; then
        python --version
        python test/test_chain.py
      fi    

      if [[ "${UPLOAD_PKG}" == "true" ]]; then
        python setup.py sdist
        python setup.py bdist_wheel --universal
      fi    
    fi

  - |
    if [[ "${UPLOAD_PKG}" == "true" ]]; then
      twine upload -u ${PYPI_USER_NAME} -p ${PYPI_PASSWORD} dist/* || true
      
      # For testing
      # twine upload -r test -u ${PYPI_USER_NAME} -p ${PYPI_PASSWORD} dist/* || true
    fi    

  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      cd doc
      npm install
      npm install moxygen -g
      doxygen Doxyfile
      node -v
      moxygen ./xml/
      cd ..
    fi

notifications:
  email: 
    - ci@bitprim.org
    - dev@bitprim.org
    - fernando@bitprim.org
  slack: bitprim:CGkcy3Bjx7UUIxu9FSZTpaxE
  webhooks:
    urls: https://webhooks.gitter.im/e/a19dd2b03bf676d2b622
    on_success: change
    on_failure: always

